services:
  app:
    build: .
    ports:
      - '4090:4090'
    environment:
      - NODE_ENV=production
      - PORT=4090
      - MONGODB_URI=mongodb://mongo:27017/pharmaceutical_shop
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_SECURE_SECRET=${VNPAY_SECURE_SECRET}
      - VNPAY_URL=${VNPAY_URL}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: pharmaceutical_shop_mongo
    ports:
      - '27018:27017' # Sử dụng port khác để tránh conflict
    environment:
      - MONGO_INITDB_DATABASE=pharmaceutical_shop
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
